config/routes.rb
Rails.application.routes.draw do

  root to: 'welcome#home'

  get '/about', to: 'welcome#about', as: "about_page"
  get '/login', to: 'sessions#new'
  post '/sessions', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  get '/users', to: 'users#index', as: 'users'
  get '/users/new', to: 'users#new', as: 'new_user'
  post '/users', to: 'users#create'
  get '/users/:user_name', to: 'users#show', as: 'user'
  get '/users/:user_name/edit', to: 'users#edit', as: 'edit_user'
  patch '/users/:user_name', to: 'users#update'
  delete '/users/:id', to: 'users#destroy'

  get '/users/:user_name/events/new', to: 'events#new', as: 'new_event'
  get '/users/:user_name/events/:id', to: 'events#show', as: 'event'
  post '/users/:user_name/events', to: 'events#create'
  get '/users/:user_name/events/:id/edit', to: 'events#edit', as: 'edit_event'
  patch '/users/:user_name/events/:id', to: 'events#update'
  delete '/users/:user_name/events/:id', to: 'events#destroy'

  get '/users/:user_name/before_after_data', to: 'users#data', as: "show_user_data"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/before_after_datum.rb
class BeforeAfterDatum < ApplicationRecord
  belongs_to :user
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :events
  has_many :patients, class_name: "User", foreign_key: "professional_id"
  belongs_to :professional, class_name: "User", optional: true

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, uniqueness: true, presence: true
  validates :user_name, uniqueness: true, presence: true

  def self.confirm params
  	@user = User.find_by({user_name: params[:user_name]})
  	@user ? @user.authenticate(params[:password]) : false
  end
  def to_label
    return self.first_name + " " + self.last_name
  end
end

app/models/visit.rb
class Visit < ActiveRecord::Base
  has_many :ahoy_events, class_name: "Ahoy::Event"
  belongs_to :user, optional: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	include SessionsHelper
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    @event = Event.all
  end

  def new
  user_name = params[:user_name]
  @user = User.find_by(user_name: user_name)
    if !current_user
      redirect_to root_path
    elsif @user.id != current_user.id
      redirect_to user_path(current_user.user_name)
    else
      @event = Event.new
    end
  end

  def create
    @event = Event.create(event_params)
    user_name = params[:user_name]
    redirect_to user_path(user_name)
  end

  def show
    event_id = params[:id]
    @event = Event.find_by(id: event_id)
    user_name = params[:user_name]
    @user = User.find_by(user_name: user_name)
  end

  def edit
    @event = Event.find_by_id(params[:id])
    user_name = params[:user_name]
    @user = User.find_by(user_name: user_name)
  end

  def update
    @event = Event.find_by_id(params[:id])
    if @event.update(event_params)
      redirect_to user_path(User.find_by_id(@event.user_id).user_name)
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @user = User.find_by_id(@event.user_id)
    @event.destroy
    redirect_to user_path(@user.user_name)
  end

  private
  def event_params
    event_info = params.require(:event).permit(:behavior, :trigger, :before, :before_notes, :after, :after_notes, :distraction, :soothing, :improving, :helpful, :hurtful, :reflection, :victory)
    event_params = event_info.merge({user_id: current_user.id})
  end

end

app/controllers/professionals_controller.rb
class ProfessionalsController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
      @user = User.new
      # render :new
  end

  def create
    user_params = params.require(:user).permit(:user_name, :password)

    @user = User.confirm(user_params)
    if @user
      login(@user)
      flash[:notice] = "Successfully logged in as #{@user.user_name}!"
      redirect_to '/users/' + @user.user_name
    else
      puts 'error'
      flash[:error] = "User Name and Password do not match"
      redirect_to login_path
    end
  end

  def destroy
    logout
    flash[:notice]= "Successfully logged out."
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login @user
      redirect_to user_path(@user.user_name)
    else
      flash[:error] =[]
      @user.errors.full_messages.each do |error|
        flash[:error] << error.to_s
      end
      redirect_to new_user_path
    end
  end

  def show
    @profs = User.where(is_prof: true)
    @user = User.find_by(user_name: params[:user_name])

    if !current_user
      redirect_to root_path
    elsif current_user.id != @user.id && current_user.id != @user.professional_id
      redirect_to user_path(current_user.user_name)
    else
      user_events = @user.events
      @events = user_events.page(params[:page]).per(5)
    end
  end

  def edit
    @user = User.find_by(user_name: params[:user_name])
    if !current_user
      redirect_to root_path
    elsif current_user.id != @user.id
      redirect_to user_path(current_user.user_name)
    end
  end

  def update
    @user = User.find_by(user_name: params[:user_name])
    if @user.update(user_params)
      redirect_to user_path
    end
  end

  def destroy
    user_name = params[:user_name]
    @user = User.find_by(user_name: user_name)
    @user.destroy
    redirect_to root_path
  end

  def data
    @user = User.find_by(user_name: params[:user_name])
    user_events = @user.events
    @events = user_events
  end

  private
  def user_params
    params.require(:user).permit(:user_name, :first_name, :last_name, :email, :professional_id, :is_prof, :password)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def home
		if current_user
			@user = current_user
		end
		@user = User.new
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/data_helper.rb
module DataHelper

  x_range = 0..10

  library_options = {
    width: 600,
    hAxis: {ticks: x_range.to_a},
  }

end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/professionals_helper.rb
module ProfessionalsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def login(user)
    session[:user_id] = user.id
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by_id(session[:user_id])
  end

  def admin
    current_user && current_user.admin
  end

  def logout
    @current_user = session[:user_id] = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/events/edit.html.erb
<aside>
  <%= image_tag("http://i.imgur.com/aT2G7y7.jpg", class: "aside-image", alt: "booger") %>
</aside>
<section>
<%= simple_form_for @event, url: '/users/' + @user.user_name + '/events/' + @event.id.to_s, method: "patch" do |f| %>
    <!-- Tabs  -->
      <div class="col s12 animated fadeIn">
          <ul class="tabs">


              <li class="tab col m3 s12"><a class="disabled deep-purple-text lighten-2 active" id="tab-one" href="#tab-activate-one">Part 1</a></li>
              <li class="tab col m3 s12"><a class="disabled deep-purple-text lighten-2" id="tab-two" href="#tab-activate-two">Part 2</a></li>
              <li class="tab col m3 s12"><a class="disabled deep-purple-text lighten-2" id="tab-three" href="#tab-activate-three">Part 3</a></li>
              <li class="tab col m3 s12"><a class="disabled deep-purple-text lighten-2" id="tab-four" href="#tab-activate-four">Part 4</a></li>

          </ul>
      </div>

  <div class="new_event_form container">
    <div class="wrapper row">
      <div class="col-m8 offset-m2">
        <div class="form_one row form-box animated fadeIn" id="form-one">
          <div class="col-m4 offset-m2">
            <%= f.input :trigger, label: "What was the prompting event?", placeholder: "What happened right before? What may have been the trigger?" %>
            <%= f.input :behavior, label: "Describe what happened.", placeholder: "What was your reaction? What did you do? What was the behavior?" %>
          </div>
          <div class="back-next-buttons">
            <%= link_to 'Cancel', '../', class: 'btn white-text' %>
            <button id="form-one-next" class="btn white-text">Next</button>
          </div>
        </div>
      <div class="form_two row form-box hidden" id="form-two">
        <div class="col-m4 offset-m2">
          <label>How did you feel before?</label>
          <span class="label">(manageable)</span>
          <br class="small-view">
          <a href="" class="disabled before-feeling" id="before-0"><div class="number-box">0</div></a>
          <a href="" class="disabled before-feeling" id="before-1"><div class="number-box">1</div></a>
          <a href="" class="disabled before-feeling" id="before-2"><div class="number-box">2</div></a>
          <a href="" class="disabled before-feeling" id="before-3"><div class="number-box">3</div></a>
          <a href="" class="disabled before-feeling" id="before-4"><div class="number-box">4</div></a>
          <a href="" class="disabled before-feeling" id="before-5"><div class="number-box">5</div></a>
          <a href="" class="disabled before-feeling" id="before-6"><div class="number-box">6</div></a>
          <a href="" class="disabled before-feeling" id="before-7"><div class="number-box">7</div></a>
          <a href="" class="disabled before-feeling" id="before-8"><div class="number-box">8</div></a>
          <a href="" class="disabled before-feeling" id="before-9"><div class="number-box">9</div></a>
          <a href="" class="disabled before-feeling" id="before-10"><div class="number-box">10</div></a>
          <span class="label small-label">(overwhelming)</span>
          <br><br>
          <%= f.input :before, :as => :hidden, :input_html => { :class => "before-input" } %>
          <%= f.input :before_notes, label: "Describe the intensity of your feelings.", placeholder: "(optional)" %>
          <label>How did you feel after?</label>
          <span class="label">(manageable)</span>
          <br class="small-view">
          <a href="" class="disabled after-feeling" id="after-0"><div class="number-box">0</div></a>
          <a href="" class="disabled after-feeling" id="after-1"><div class="number-box">1</div></a>
          <a href="" class="disabled after-feeling" id="after-2"><div class="number-box">2</div></a>
          <a href="" class="disabled after-feeling" id="after-3"><div class="number-box">3</div></a>
          <a href="" class="disabled after-feeling" id="after-4"><div class="number-box">4</div></a>
          <a href="" class="disabled after-feeling" id="after-5"><div class="number-box">5</div></a>
          <a href="" class="disabled after-feeling" id="after-6"><div class="number-box">6</div></a>
          <a href="" class="disabled after-feeling" id="after-7"><div class="number-box">7</div></a>
          <a href="" class="disabled after-feeling" id="after-8"><div class="number-box">8</div></a>
          <a href="" class="disabled after-feeling" id="after-9"><div class="number-box">9</div></a>
          <a href="" class="disabled after-feeling" id="after-10"><div class="number-box">10</div></a>
          <span class="label small-label">(overwhelming)</span>
          <br><br>
          <%= f.input :after, :as => :hidden, :input_html => { :class => "after-input" } %>
          <%= f.input :after_notes, label: "Describe how your feelings changed.", placeholder: "(optional)" %>
        </div>
        <div class="back-next-buttons">
            <button id="form-two-back" class="btn white-text">Back</button>
            <button id="form-two-next" class="btn white-text">Next</button>
        </div>
      </div>
      <div class="form_three row form-box hidden" id="form-three">
        <div class="col-m4 offset-m2">
          <label>Which of the following stressors did the behavior help alleviate?</label>
          <a href="" class="disabled reason-box" id="checkbox-1"><div class="checkbox">Needed a Distraction</div></a>
          <a href="" class="disabled reason-box" id="checkbox-2"><div class="checkbox">Self-Soothing</div></a>
          <a href="" class="disabled reason-box" id="checkbox-3"><div class="checkbox">Improving the Moment</div></a>
          <%= f.input :distraction, :as => :hidden, :input_html => { :value => false, :id => "input-checkbox-1" } %>
          <%= f.input :soothing, :as => :hidden, :input_html => { :value => false, :id => "input-checkbox-2" } %>
          <%= f.input :improving, :as => :hidden, :input_html => { :value => false, :id => "input-checkbox-3" } %>
          <br><br>
          <%= f.input :helpful, label: "How did the behavior help you?" %>
          <%= f.input :hurtful, label: "How did the behavior hurt you?" %>
        </div>
        <div class="back-next-buttons">
            <button id="form-three-back" class="btn white-text">Back</button>
            <button id="form-three-next" class="btn white-text">Next</button>
        </div>
      </div>
      <div class="page_four row form-box hidden" id="form-four">
        <div class="form_four col-m4 offset-m2">
          <%= f.input :reflection, label: "What could you have done differently?", placeholder: "Reflect on what you would want to do next time." %>
          <%= f.input :victory, label: "What are you proud of?", placeholder: "Claim your victories!" %>
        </div>
        <div class="back-next-buttons">
            <button id="form-four-back" class="btn white-text">Back</button>
            <button id="form-save-button" class="btn white-text">Save</button>
        </div>
  <% end %>
</div>


</section>

app/views/events/new.html.erb
<aside>
  <%= image_tag("http://i.imgur.com/aT2G7y7.jpg", class: "aside-image", alt: "booger") %>
</aside>
<section>
<%= simple_form_for @event, url: '/users/' + @user.user_name + '/events/', class: "no-enter-form", method: "post" do |f| %>
    <!-- Tabs  -->
      <div class="col s12 animated fadeIn">
          <ul class="tabs">


              <li class="tab col m3 s12"><a class="disabled deep-purple-text lighten-2 active" id="tab-one" href="#tab-activate-one">Part 1</a></li>
              <li class="tab col m3 s12"><a class="disabled deep-purple-text lighten-2" id="tab-two" href="#tab-activate-two">Part 2</a></li>
              <li class="tab col m3 s12"><a class="disabled deep-purple-text lighten-2" id="tab-three" href="#tab-activate-three">Part 3</a></li>
              <li class="tab col m3 s12"><a class="disabled deep-purple-text lighten-2" id="tab-four" href="#tab-activate-four">Part 4</a></li>

          </ul>
      </div>

  <div class="new_event_form container">
    <div class="wrapper row">
      <div class="col-m8 offset-m2">
        <div class="form_one row form-box animated fadeIn" id="form-one">
          <div class="col-m4 offset-m2">
            <%= f.input :trigger, label: "What was the prompting event?", placeholder: "What happened right before? What may have been the trigger?" %>
            <%= f.input :behavior, label: "Describe what happened.", placeholder: "What was your reaction? What did you do? What was the behavior?" %>
          </div>
          <div class="back-next-buttons">
            <%= link_to 'Cancel', '../', class: 'btn white-text' %>
            <button id="form-one-next" class="btn white-text">Next</button>
          </div>
        </div>
      <div class="form_two row form-box hidden" id="form-two">
        <div class="col-m4 offset-m2">
          <label>How did you feel before?</label>
          <span class="label">(manageable)</span>
          <br class="small-view">
          <a href="" class="disabled before-feeling" id="before-0"><div class="number-box">0</div></a>
          <a href="" class="disabled before-feeling" id="before-1"><div class="number-box">1</div></a>
          <a href="" class="disabled before-feeling" id="before-2"><div class="number-box">2</div></a>
          <a href="" class="disabled before-feeling" id="before-3"><div class="number-box">3</div></a>
          <a href="" class="disabled before-feeling" id="before-4"><div class="number-box">4</div></a>
          <a href="" class="disabled before-feeling" id="before-5"><div class="number-box">5</div></a>
          <a href="" class="disabled before-feeling" id="before-6"><div class="number-box">6</div></a>
          <a href="" class="disabled before-feeling" id="before-7"><div class="number-box">7</div></a>
          <a href="" class="disabled before-feeling" id="before-8"><div class="number-box">8</div></a>
          <a href="" class="disabled before-feeling" id="before-9"><div class="number-box">9</div></a>
          <a href="" class="disabled before-feeling" id="before-10"><div class="number-box">10</div></a>
          <span class="label small-label">(overwhelming)</span>
          <br><br>
          <%= f.input :before, :as => :hidden, :input_html => { :class => "before-input" } %>
          <%= f.input :before_notes, label: "Describe the intensity of your feelings.", placeholder: "(optional)" %>
          <label>How did you feel after?</label>
          <span class="label">(manageable)</span>
          <br class="small-view">
          <a href="" class="disabled after-feeling" id="after-0"><div class="number-box">0</div></a>
          <a href="" class="disabled after-feeling" id="after-1"><div class="number-box">1</div></a>
          <a href="" class="disabled after-feeling" id="after-2"><div class="number-box">2</div></a>
          <a href="" class="disabled after-feeling" id="after-3"><div class="number-box">3</div></a>
          <a href="" class="disabled after-feeling" id="after-4"><div class="number-box">4</div></a>
          <a href="" class="disabled after-feeling" id="after-5"><div class="number-box">5</div></a>
          <a href="" class="disabled after-feeling" id="after-6"><div class="number-box">6</div></a>
          <a href="" class="disabled after-feeling" id="after-7"><div class="number-box">7</div></a>
          <a href="" class="disabled after-feeling" id="after-8"><div class="number-box">8</div></a>
          <a href="" class="disabled after-feeling" id="after-9"><div class="number-box">9</div></a>
          <a href="" class="disabled after-feeling" id="after-10"><div class="number-box">10</div></a>
          <span class="label small-label">(overwhelming)</span>
          <br><br>
          <%= f.input :after, :as => :hidden, :input_html => { :class => "after-input" } %>
          <%= f.input :after_notes, label: "Describe how your feelings changed.", placeholder: "(optional)" %>
        </div>
        <div class="back-next-buttons">
            <button id="form-two-back" class="btn white-text">Back</button>
            <button id="form-two-next" class="btn white-text">Next</button>
        </div>
      </div>
      <div class="form_three row form-box hidden" id="form-three">
        <div class="col-m4 offset-m2">
          <label>Which of the following stressors did the behavior help alleviate?</label>
          <a href="" class="disabled reason-box" id="checkbox-1"><div class="checkbox">Needed a Distraction</div></a>
          <a href="" class="disabled reason-box" id="checkbox-2"><div class="checkbox">Self-Soothing</div></a>
          <a href="" class="disabled reason-box" id="checkbox-3"><div class="checkbox">Improving the Moment</div></a>
          <%= f.input :distraction, :as => :hidden, :input_html => { :value => false, :id => "input-checkbox-1" } %>
          <%= f.input :soothing, :as => :hidden, :input_html => { :value => false, :id => "input-checkbox-2" } %>
          <%= f.input :improving, :as => :hidden, :input_html => { :value => false, :id => "input-checkbox-3" } %>
          <br><br>
          <%= f.input :helpful, label: "How did the behavior help you?" %>
          <%= f.input :hurtful, label: "How did the behavior hurt you?" %>
        </div>
        <div class="back-next-buttons">
            <button id="form-three-back" class="btn white-text">Back</button>
            <button id="form-three-next" class="btn white-text">Next</button>
        </div>
      </div>
      <div class="page_four row form-box hidden" id="form-four">
        <div class="form_four col-m4 offset-m2">
          <%= f.input :reflection, label: "What could you have done differently?", placeholder: "Reflect on what you would want to do next time." %>
          <%= f.input :victory, label: "What are you proud of?", placeholder: "Claim your victories!" %>
        </div>
        <div class="back-next-buttons">
            <button id="form-four-back" class="btn white-text">Back</button>
            <button id="form-save-button" class="btn white-text">Save</button>
        </div>
  <% end %>
</div>


</section>

app/views/events/show.html.erb
<aside>
	<%= image_tag("http://i.imgur.com/aT2G7y7.jpg", class: "aside-image", alt: "mountains") %>
</aside>
<section id="overflow-section">
	<div>
		<h4><%= @user.first_name %> <%= @user.last_name %></h4>
	</div>

	<div class="container">
		<div class="row">
			<div class="form-box clearfix animated fadeIn"  id="show-event-div">
				<div id="events-container-2" class="col s6">
					<div class="event-buttons">
						<a class="waves-effect waves-light btn" id="edit-event-button"><%= button_to 'Edit Event', edit_event_path(@user.user_name, @event), {method: 'get'} %></a>
						<a class="waves-effect waves-light btn" id="delete-event-button"><%= button_to 'Delete Event', event_path(@event), method: :delete, data: {confirm: 'Are you sure you want to delete this post?' }%></a>
					</div>
					<div>
						<p><span class="bold">Entry created: </span><%= @event.created_at.strftime("%b. %d, %Y") %></p>
						<p><span class="bold">Last updated: </span><%= @event.updated_at.strftime("%b. %d, %Y") %></p>
						<h3><span class="bold">Mindfulness:</span></h3><hr>
						<p><span class="bold">The trigger that prompted my behavior was: </span><br>
							<%= @event.trigger %></p>
						<p><span class="bold">My behavior: </span><br>
							<%= @event.behavior %></p>
						<h3><span class="bold">Emotional Regulation:</span></h3><hr>
						<p><span class="bold">On a scale of 1 - 10, before I felt like: </span><%= @event.before %></p>
						<% if @event.before_notes %>
							<p>
								<span class="bold">Describe the intensity of your feelings. </span><br>
								<%= @event.before_notes %>
							</p>
						<% end %>
						<p><span class="bold">On a scale of 1 - 10, after I felt like: </span><%= @event.after %></p>
						<% if @event.after_notes %>
							<p>
								<span class="bold">Describe how your feelings changed. </span><br>
								<%= @event.after_notes %>
							</p>
						<% end %>
						<h3><span class="bold">Distress Tolerance:</span></h3><hr>
						<p><span class="bold">My behavior was prompted by a need:</p></span>
						<p><span class="bold">To Find a Distraction: </span><%= @event.distraction %></p>
						<p><span class="bold">To Self Soothe: </span><%= @event.soothing %></p>
						<p><span class="bold">To Improve the Moment: </span><%= @event.improving %></p>
						<p><span class="bold">The way this behavior helped me: </span><br>
							<%= @event.helpful %></p>
						<p><span class="bold">The way this behavior hurt me: </span><br>
							<%= @event.hurtful %></p>
						<h3><span class="bold">Increase Positivity:</span></h3><hr>
						<p><span class="bold">Things I could have done differently: </span><br>
							<%= @event.reflection %></p>
						<p><span class="bold">I am strong and I am proud because: </span><br>
							<%= @event.victory %></p>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Within Reach Recovery App</title>

    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- font family -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">

    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/css/materialize.min.css">

  </head>

  <body>

    <nav class="top-nav" id="navbar">
      <div class="nav-wrapper">
        <% if current_user %>
        <span class="app-name"><%= link_to "Within Reach", user_path(current_user.user_name), class: "brand-logo" %></span>
        <% else %>
          <span class="app-name"><%= link_to "Within Reach", login_path, class: "brand-logo" %></span>
          <% end %>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
          <% if current_user %>
            <li><%= link_to "Profile", user_path(current_user.user_name)%></li>

            <li><%= link_to "Log Out", logout_path, class:"last-nav" %></li>
          <% else %>
            <li><%= link_to "Create Account", new_user_path %></li>
            <li><%= link_to "Log In", login_path, class:"last-nav" %></li>
          <% end %>
        </ul>
      </div>
    </nav>
    <% flash.each do |_key, msg| %>
      <% if msg.kind_of?(Array) %>
        <% iterator = 0 %>
        <% msg.each do |text| %>
          <script type="text/javascript">
            Materialize.toast('<%= text %>', 4000)
          </script>
            <% iterator += 1 %>
          <% end %>
      <% else %>
        <script type="text/javascript">
          Materialize.toast('<%= msg %>', 4000)
        </script>
      <% end %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/users/_admin_show.html.erb
<h2> My patients: </h2>
<% if !@user.patients.empty? %>
	<ul>
		<% for user in @user.patients %>
			<li><h5>
			<%= link_to user.first_name, '/users/' + user.user_name %>
		</h5></li>
		<% end %>
	</ul>
<% else %>
<p>You have no patients at this time</p>
<% end %>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

<div class="container">
<div class="white-tainer">
	<div class="form-box">
		<%= simple_form_for @user do |f| %>
		<%= f.input :email, :as => :string, :type => :email  %>
		<%= f.input :first_name, :as => :string %>
		<%= f.input :last_name, :as => :string %>
		<%= f.input :user_name, :as => :string %>
		<%= f.input :password %>
		<%= f.button :submit %>
		<% end %>
	</div>
</div>
</div>

app/views/users/show.html.erb
<aside>
<%= image_tag("http://i.imgur.com/aT2G7y7.jpg", class: "aside-image", alt: "booger") %>
</aside>

<section>

		<h4><%= @user.first_name %> <%= @user.last_name %></h4>
    <div class="container animate fadeIn">
      <div class="row">
        <%= link_to "Log Out", logout_path, class: "btn spaced-btn centered small-view" %>
        <div class="form-box clearfix">
          <div id="events-container" class="col s6">
						<% if !@user.is_prof && current_user == @user  %>
							<button class="btn" id="new-event-button"><%= link_to 'New Entry', '/users/' + current_user.user_name + '/events/new'%></button>

						<h3><%= @user.professional_id && current_user.id == @user.professional_id ? @user.first_name + "'s" : "Your"  %> Entries</h3>
						<div id="nav"><%= paginate @events if @events %></div>
						<% end %>
		        <ul>
		          <% for event in @events %>
		            <li id="event-lists">
		              <p>
		                <%= link_to event.created_at.strftime("%b. %d, %Y"), '/users/' + @user.user_name + '/events/' + event.id.to_s %><br>
										Triggering Event: <%= truncate(event.trigger) %><br>
										Behavior: <%= truncate(event.behavior) %>
									</p>
		            </li>
		            <hr>
		          <% end %>
		        </ul>
		      </div>
					<div class="col <%= @user.is_prof && @user == current_user ? 's8 offset-s3' : 's6'%>" id="#prof-container">
						<% if !@user.professional && !@user.is_prof %>
						<p>You aren't sharing with a professional yet. If your doctor is listed below, you may select them to share your events with.</p>
						<%= simple_form_for @user, url: '/users/' + @user.user_name, method: 'patch' do |f| %>
							<%= f.input :professional_id, collection: @profs %>
							<%= f.button :submit, 'Choose' %>
						<% end %>
						<% elsif !@user.is_prof && current_user == @user %>
							<h5> Your professional is <%= User.find_by_id(@user.professional_id).first_name + " " + User.find_by_id(@user.professional_id).last_name %> </h5>
						<% end %>
						<%= render partial: "admin_show" if @user.is_prof? %>
					</div>
				</div>
			</div>
		</div>
</section>